name: test
on:
  push:
    branches:
      - '*'

jobs:                                                
  test:                                      
    uses: ./.github/workflows/_template.test.yaml
